"""initial schema

Revision ID: 0001
Revises: 
Create Date: 2026-09-28 04:33:56.220395

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

import app.models.types
from app.models.guards import install_db_guards


# revision identifiers, used by Alembic.
revision: str = '0001'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('asset_product_mapping',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('vendor_norm', sa.String(length=128), nullable=False),
    sa.Column('product_norm', sa.String(length=128), nullable=False),
    sa.Column('cpe_part', sa.String(length=1), nullable=False),
    sa.Column('cpe_vendor', sa.String(length=128), nullable=False),
    sa.Column('cpe_product', sa.String(length=128), nullable=False),
    sa.Column('decision', sa.Enum('approved', 'rejected', name='ck_mapping_decision', native_enum=False, create_constraint=True, length=16), nullable=False),
    sa.Column('decided_by', sa.String(length=64), nullable=False),
    sa.Column('decided_at', app.models.types.UTCDateTime(), nullable=False),
    sa.Column('reason', sa.String(length=512), nullable=True),
    sa.CheckConstraint("decision IN ('approved', 'rejected')", name='ck_mapping_decision'),
    sa.CheckConstraint("decision IN ('approved', 'rejected')", name='ck_mapping_decision'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('vendor_norm', 'product_norm', 'cpe_part', 'cpe_vendor', 'cpe_product', name='uq_product_mapping')
    )
    with op.batch_alter_table('asset_product_mapping', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_asset_product_mapping_product_norm'), ['product_norm'], unique=False)
        batch_op.create_index(batch_op.f('ix_asset_product_mapping_vendor_norm'), ['vendor_norm'], unique=False)

    op.create_table('audit_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('occurred_at', app.models.types.UTCDateTime(), nullable=False),
    sa.Column('actor', sa.String(length=64), nullable=False),
    sa.Column('actor_role', sa.String(length=16), nullable=True),
    sa.Column('action', sa.String(length=64), nullable=False),
    sa.Column('target_type', sa.String(length=64), nullable=True),
    sa.Column('target_id', sa.String(length=128), nullable=True),
    sa.Column('before', sa.JSON(), nullable=True),
    sa.Column('after', sa.JSON(), nullable=True),
    sa.Column('client_ip', sa.String(length=45), nullable=True),
    sa.Column('result', sa.String(length=16), nullable=False),
    sa.Column('prev_hash', sa.String(length=64), nullable=False),
    sa.Column('hash', sa.String(length=64), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('hash')
    )
    with op.batch_alter_table('audit_logs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_audit_logs_action'), ['action'], unique=False)
        batch_op.create_index(batch_op.f('ix_audit_logs_actor'), ['actor'], unique=False)
        batch_op.create_index(batch_op.f('ix_audit_logs_occurred_at'), ['occurred_at'], unique=False)

    op.create_table('collection_history',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('source', sa.Enum('NVD', 'EPSS', 'KEV', 'BUNDLE', 'ALL', name='ck_coll_source', native_enum=False, create_constraint=True, length=14), nullable=False),
    sa.Column('trigger', sa.Enum('schedule', 'manual', 'import', name='ck_coll_trigger', native_enum=False, create_constraint=True, length=16), nullable=False),
    sa.Column('requested_by', sa.String(length=64), nullable=False),
    sa.Column('started_at', app.models.types.UTCDateTime(), nullable=False),
    sa.Column('finished_at', app.models.types.UTCDateTime(), nullable=True),
    sa.Column('status', sa.Enum('running', 'success', 'partial', 'failed', name='ck_coll_status', native_enum=False, create_constraint=True, length=15), nullable=False),
    sa.Column('params', sa.JSON(), nullable=False),
    sa.Column('endpoints_called', sa.JSON(), nullable=False),
    sa.Column('items_fetched', sa.Integer(), nullable=False),
    sa.Column('items_inserted', sa.Integer(), nullable=False),
    sa.Column('items_updated', sa.Integer(), nullable=False),
    sa.Column('error_summary', sa.String(length=1000), nullable=True),
    sa.Column('bundle_sha256', sa.String(length=64), nullable=True),
    sa.CheckConstraint("source IN ('NVD', 'EPSS', 'KEV', 'BUNDLE', 'ALL')", name='ck_coll_source'),
    sa.CheckConstraint("source IN ('NVD', 'EPSS', 'KEV', 'BUNDLE', 'ALL')", name='ck_coll_source'),
    sa.CheckConstraint("status IN ('running', 'success', 'partial', 'failed')", name='ck_coll_status'),
    sa.CheckConstraint("status IN ('running', 'success', 'partial', 'failed')", name='ck_coll_status'),
    sa.CheckConstraint('"trigger" IN (\'schedule\', \'manual\', \'import\')', name='ck_coll_trigger'),
    sa.CheckConstraint('"trigger" IN (\'schedule\', \'manual\', \'import\')', name='ck_coll_trigger'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('import_batches',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('stored_file_id', sa.String(length=36), nullable=False),
    sa.Column('original_filename', sa.String(length=255), nullable=False),
    sa.Column('sha256', sa.String(length=64), nullable=False),
    sa.Column('size_bytes', sa.Integer(), nullable=False),
    sa.Column('row_count', sa.Integer(), nullable=False),
    sa.Column('error_count', sa.Integer(), nullable=False),
    sa.Column('uploaded_by', sa.String(length=64), nullable=False),
    sa.Column('uploaded_at', app.models.types.UTCDateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('stored_file_id')
    )
    op.create_table('job_locks',
    sa.Column('name', sa.String(length=64), nullable=False),
    sa.Column('holder', sa.String(length=128), nullable=False),
    sa.Column('acquired_at', app.models.types.UTCDateTime(), nullable=False),
    sa.Column('expires_at', app.models.types.UTCDateTime(), nullable=False),
    sa.PrimaryKeyConstraint('name')
    )
    op.create_table('policy_versions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('version', sa.String(length=64), nullable=False),
    sa.Column('content_yaml', sa.Text(), nullable=False),
    sa.Column('content_sha256', sa.String(length=64), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_by', sa.String(length=64), nullable=False),
    sa.Column('created_at', app.models.types.UTCDateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('version')
    )
    with op.batch_alter_table('policy_versions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_policy_versions_is_active'), ['is_active'], unique=False)

    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=64), nullable=False),
    sa.Column('password_hash', sa.String(length=256), nullable=False),
    sa.Column('role', sa.Enum('viewer', 'operator', 'admin', name='ck_user_role', native_enum=False, create_constraint=True, length=16), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('failed_login_count', sa.Integer(), nullable=False),
    sa.Column('locked_until', app.models.types.UTCDateTime(), nullable=True),
    sa.Column('created_at', app.models.types.UTCDateTime(), nullable=False),
    sa.Column('last_login_at', app.models.types.UTCDateTime(), nullable=True),
    sa.CheckConstraint("role IN ('viewer', 'operator', 'admin')", name='ck_user_role'),
    sa.CheckConstraint("role IN ('viewer', 'operator', 'admin')", name='ck_user_role'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('username')
    )
    op.create_table('vulnerabilities',
    sa.Column('cve_id', sa.String(length=32), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('published_at', app.models.types.UTCDateTime(), nullable=True),
    sa.Column('last_modified_at', app.models.types.UTCDateTime(), nullable=True),
    sa.Column('nvd_vuln_status', sa.String(length=32), nullable=True),
    sa.Column('cvss_version', sa.String(length=8), nullable=True),
    sa.Column('cvss_score', sa.Float(), nullable=True),
    sa.Column('cvss_vector', sa.String(length=256), nullable=True),
    sa.Column('cvss_source', sa.String(length=128), nullable=True),
    sa.Column('cvss_type', sa.String(length=16), nullable=True),
    sa.Column('nvd_raw_sha256', sa.String(length=64), nullable=True),
    sa.Column('kev', sa.Boolean(), nullable=False),
    sa.Column('kev_date_added', sa.Date(), nullable=True),
    sa.Column('kev_due_date', sa.Date(), nullable=True),
    sa.Column('kev_ransomware', sa.String(length=16), nullable=True),
    sa.Column('epss_initial', sa.Float(), nullable=True),
    sa.Column('epss_initial_date', sa.Date(), nullable=True),
    sa.Column('epss_first_seen_at', app.models.types.UTCDateTime(), nullable=True),
    sa.Column('epss_current', sa.Float(), nullable=True),
    sa.Column('epss_current_percentile', sa.Float(), nullable=True),
    sa.Column('epss_current_date', sa.Date(), nullable=True),
    sa.Column('epss_last_updated_at', app.models.types.UTCDateTime(), nullable=True),
    sa.Column('first_collected_at', app.models.types.UTCDateTime(), nullable=False),
    sa.Column('last_collected_at', app.models.types.UTCDateTime(), nullable=False),
    sa.CheckConstraint('cvss_score IS NULL OR (cvss_score >= 0 AND cvss_score <= 10)', name='ck_vuln_cvss_range'),
    sa.CheckConstraint('epss_current IS NULL OR (epss_current >= 0 AND epss_current <= 1)', name='ck_vuln_epss_current_range'),
    sa.CheckConstraint('epss_initial IS NULL OR (epss_initial >= 0 AND epss_initial <= 1)', name='ck_vuln_epss_initial_range'),
    sa.PrimaryKeyConstraint('cve_id')
    )
    with op.batch_alter_table('vulnerabilities', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_vulnerabilities_cvss_score'), ['cvss_score'], unique=False)
        batch_op.create_index(batch_op.f('ix_vulnerabilities_kev'), ['kev'], unique=False)
        batch_op.create_index(batch_op.f('ix_vulnerabilities_last_modified_at'), ['last_modified_at'], unique=False)

    op.create_table('assets',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('asset_code', sa.String(length=64), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('zone', sa.Enum('경계면', '내부', name='ck_asset_zone', native_enum=False, create_constraint=True, length=11), nullable=False),
    sa.Column('ip', sa.String(length=45), nullable=True),
    sa.Column('criticality', sa.Enum('상', '중', '하', name='ck_asset_criticality', native_enum=False, create_constraint=True, length=9), nullable=False),
    sa.Column('owner_name', sa.String(length=64), nullable=True),
    sa.Column('department', sa.String(length=128), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('import_batch_id', sa.Integer(), nullable=True),
    sa.Column('created_at', app.models.types.UTCDateTime(), nullable=False),
    sa.Column('updated_at', app.models.types.UTCDateTime(), nullable=False),
    sa.CheckConstraint("criticality IN ('상', '중', '하')", name='ck_asset_criticality'),
    sa.CheckConstraint("criticality IN ('상', '중', '하')", name='ck_asset_criticality'),
    sa.CheckConstraint("zone IN ('경계면', '내부')", name='ck_asset_zone'),
    sa.CheckConstraint("zone IN ('경계면', '내부')", name='ck_asset_zone'),
    sa.ForeignKeyConstraint(['import_batch_id'], ['import_batches.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('assets', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_assets_asset_code'), ['asset_code'], unique=True)
        batch_op.create_index(batch_op.f('ix_assets_ip'), ['ip'], unique=False)
        batch_op.create_index(batch_op.f('ix_assets_name'), ['name'], unique=False)
        batch_op.create_index(batch_op.f('ix_assets_owner_name'), ['owner_name'], unique=False)

    op.create_table('epss_history',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('cve_id', sa.String(length=32), nullable=False),
    sa.Column('epss', sa.Float(), nullable=False),
    sa.Column('percentile', sa.Float(), nullable=True),
    sa.Column('score_date', sa.Date(), nullable=False),
    sa.Column('collected_at', app.models.types.UTCDateTime(), nullable=False),
    sa.Column('collection_id', sa.Integer(), nullable=True),
    sa.CheckConstraint('epss >= 0 AND epss <= 1', name='ck_epss_hist_range'),
    sa.CheckConstraint('percentile IS NULL OR (percentile >= 0 AND percentile <= 1)', name='ck_epss_hist_pct_range'),
    sa.ForeignKeyConstraint(['collection_id'], ['collection_history.id'], ),
    sa.ForeignKeyConstraint(['cve_id'], ['vulnerabilities.cve_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('cve_id', 'score_date', name='uq_epss_cve_date')
    )
    with op.batch_alter_table('epss_history', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_epss_history_cve_id'), ['cve_id'], unique=False)

    op.create_table('vulnerability_products',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('cve_id', sa.String(length=32), nullable=False),
    sa.Column('config_index', sa.Integer(), nullable=False),
    sa.Column('config_operator', sa.String(length=3), nullable=True),
    sa.Column('node_index', sa.Integer(), nullable=False),
    sa.Column('node_operator', sa.String(length=3), nullable=False),
    sa.Column('node_negate', sa.Boolean(), nullable=False),
    sa.Column('match_index', sa.Integer(), nullable=False),
    sa.Column('vulnerable', sa.Boolean(), nullable=False),
    sa.Column('criteria', sa.String(length=512), nullable=False),
    sa.Column('match_criteria_id', sa.String(length=64), nullable=True),
    sa.Column('part', sa.String(length=1), nullable=False),
    sa.Column('vendor', sa.String(length=128), nullable=False),
    sa.Column('product', sa.String(length=128), nullable=False),
    sa.Column('version', sa.String(length=64), nullable=False),
    sa.Column('version_start_including', sa.String(length=64), nullable=True),
    sa.Column('version_start_excluding', sa.String(length=64), nullable=True),
    sa.Column('version_end_including', sa.String(length=64), nullable=True),
    sa.Column('version_end_excluding', sa.String(length=64), nullable=True),
    sa.ForeignKeyConstraint(['cve_id'], ['vulnerabilities.cve_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('cve_id', 'config_index', 'node_index', 'match_index', name='uq_vuln_product_pos')
    )
    with op.batch_alter_table('vulnerability_products', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_vulnerability_products_cve_id'), ['cve_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_vulnerability_products_product'), ['product'], unique=False)
        batch_op.create_index(batch_op.f('ix_vulnerability_products_vendor'), ['vendor'], unique=False)

    op.create_table('asset_products',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('asset_id', sa.Integer(), nullable=False),
    sa.Column('vendor_raw', sa.String(length=128), nullable=True),
    sa.Column('product_raw', sa.String(length=128), nullable=True),
    sa.Column('version_raw', sa.String(length=64), nullable=True),
    sa.Column('cpe_raw', sa.String(length=512), nullable=True),
    sa.Column('vendor_norm', sa.String(length=128), nullable=True),
    sa.Column('product_norm', sa.String(length=128), nullable=True),
    sa.Column('version_norm', sa.String(length=64), nullable=True),
    sa.Column('update_norm', sa.String(length=64), nullable=True),
    sa.Column('cpe_normalized', sa.String(length=512), nullable=True),
    sa.Column('cpe_source', sa.String(length=16), nullable=True),
    sa.Column('cpe_error', sa.String(length=255), nullable=True),
    sa.ForeignKeyConstraint(['asset_id'], ['assets.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('asset_id', 'vendor_norm', 'product_norm', 'version_norm', name='uq_asset_product')
    )
    with op.batch_alter_table('asset_products', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_asset_products_asset_id'), ['asset_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_asset_products_cpe_normalized'), ['cpe_normalized'], unique=False)
        batch_op.create_index(batch_op.f('ix_asset_products_product_norm'), ['product_norm'], unique=False)
        batch_op.create_index(batch_op.f('ix_asset_products_vendor_norm'), ['vendor_norm'], unique=False)

    op.create_table('asset_vulnerabilities',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('asset_id', sa.Integer(), nullable=False),
    sa.Column('asset_product_id', sa.Integer(), nullable=False),
    sa.Column('cve_id', sa.String(length=32), nullable=False),
    sa.Column('assessment_state', sa.Enum('assessed', 'epss_pending', name='ck_av_assessment_state', native_enum=False, create_constraint=True, length=20), nullable=False),
    sa.Column('severity', sa.String(length=32), nullable=True),
    sa.Column('severity_rank', sa.Integer(), nullable=True),
    sa.Column('detected_at', app.models.types.UTCDateTime(), nullable=False),
    sa.Column('initial_due_at', app.models.types.UTCDateTime(), nullable=True),
    sa.Column('due_at', app.models.types.UTCDateTime(), nullable=True),
    sa.Column('owner', sa.String(length=64), nullable=True),
    sa.Column('status', sa.Enum('신규', '확인중', '조치예정', '조치중', '조치완료', '예외처리', '오탐', name='ck_av_status', native_enum=False, create_constraint=True, length=12), nullable=False),
    sa.Column('match_type', sa.Enum('CPE_EXACT', 'CPE_RANGE', 'CPE_ALL_VERSIONS', 'APPROVED_MAPPING', name='ck_av_match_type', native_enum=False, create_constraint=True, length=24), nullable=False),
    sa.Column('match_confidence', sa.Integer(), nullable=True),
    sa.Column('match_evidence', sa.JSON(), nullable=False),
    sa.Column('mapping_approved_by', sa.String(length=64), nullable=True),
    sa.Column('policy_version_id', sa.Integer(), nullable=True),
    sa.Column('needs_revalidation', sa.Boolean(), nullable=False),
    sa.Column('created_at', app.models.types.UTCDateTime(), nullable=False),
    sa.Column('updated_at', app.models.types.UTCDateTime(), nullable=False),
    sa.CheckConstraint("assessment_state IN ('assessed', 'epss_pending')", name='ck_av_assessment_state'),
    sa.CheckConstraint("assessment_state IN ('assessed', 'epss_pending')", name='ck_av_assessment_state'),
    sa.CheckConstraint("match_type IN ('CPE_EXACT', 'CPE_RANGE', 'CPE_ALL_VERSIONS', 'APPROVED_MAPPING')", name='ck_av_match_type'),
    sa.CheckConstraint("match_type IN ('CPE_EXACT', 'CPE_RANGE', 'CPE_ALL_VERSIONS', 'APPROVED_MAPPING')", name='ck_av_match_type'),
    sa.CheckConstraint("status IN ('신규', '확인중', '조치예정', '조치중', '조치완료', '예외처리', '오탐')", name='ck_av_status'),
    sa.CheckConstraint("status IN ('신규', '확인중', '조치예정', '조치중', '조치완료', '예외처리', '오탐')", name='ck_av_status'),
    sa.ForeignKeyConstraint(['asset_id'], ['assets.id'], ),
    sa.ForeignKeyConstraint(['asset_product_id'], ['asset_products.id'], ),
    sa.ForeignKeyConstraint(['cve_id'], ['vulnerabilities.cve_id'], ),
    sa.ForeignKeyConstraint(['policy_version_id'], ['policy_versions.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('asset_product_id', 'cve_id', name='uq_asset_vuln')
    )
    with op.batch_alter_table('asset_vulnerabilities', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_asset_vulnerabilities_asset_id'), ['asset_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_asset_vulnerabilities_asset_product_id'), ['asset_product_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_asset_vulnerabilities_cve_id'), ['cve_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_asset_vulnerabilities_due_at'), ['due_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_asset_vulnerabilities_owner'), ['owner'], unique=False)
        batch_op.create_index(batch_op.f('ix_asset_vulnerabilities_severity'), ['severity'], unique=False)
        batch_op.create_index(batch_op.f('ix_asset_vulnerabilities_status'), ['status'], unique=False)

    op.create_table('mapping_candidates',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('asset_product_id', sa.Integer(), nullable=False),
    sa.Column('cve_id', sa.String(length=32), nullable=True),
    sa.Column('proposed_cpe', sa.String(length=512), nullable=False),
    sa.Column('level', sa.Integer(), nullable=False),
    sa.Column('confidence', sa.Integer(), nullable=True),
    sa.Column('breakdown', sa.JSON(), nullable=False),
    sa.Column('reason', sa.String(length=512), nullable=False),
    sa.Column('status', sa.Enum('pending', 'approved', 'rejected', name='ck_candidate_status', native_enum=False, create_constraint=True, length=16), nullable=False),
    sa.Column('created_at', app.models.types.UTCDateTime(), nullable=False),
    sa.Column('decided_by', sa.String(length=64), nullable=True),
    sa.Column('decided_at', app.models.types.UTCDateTime(), nullable=True),
    sa.CheckConstraint("status IN ('pending', 'approved', 'rejected')", name='ck_candidate_status'),
    sa.CheckConstraint("status IN ('pending', 'approved', 'rejected')", name='ck_candidate_status'),
    sa.ForeignKeyConstraint(['asset_product_id'], ['asset_products.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['cve_id'], ['vulnerabilities.cve_id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('asset_product_id', 'cve_id', 'proposed_cpe', name='uq_candidate')
    )
    with op.batch_alter_table('mapping_candidates', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_mapping_candidates_asset_product_id'), ['asset_product_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_mapping_candidates_cve_id'), ['cve_id'], unique=False)

    op.create_table('status_history',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('asset_vulnerability_id', sa.Integer(), nullable=False),
    sa.Column('from_status', sa.String(length=16), nullable=True),
    sa.Column('to_status', sa.String(length=16), nullable=False),
    sa.Column('changed_by', sa.String(length=64), nullable=False),
    sa.Column('changed_at', app.models.types.UTCDateTime(), nullable=False),
    sa.Column('comment', sa.String(length=1000), nullable=True),
    sa.ForeignKeyConstraint(['asset_vulnerability_id'], ['asset_vulnerabilities.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('status_history', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_status_history_asset_vulnerability_id'), ['asset_vulnerability_id'], unique=False)

    op.create_table('vulnerability_assessments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('asset_vulnerability_id', sa.Integer(), nullable=False),
    sa.Column('policy_version_id', sa.Integer(), nullable=False),
    sa.Column('assessment_state', sa.Enum('assessed', 'epss_pending', name='ck_va_assessment_state', native_enum=False, create_constraint=True, length=20), nullable=False),
    sa.Column('severity', sa.String(length=32), nullable=True),
    sa.Column('zone', sa.Enum('경계면', '내부', name='ck_va_zone', native_enum=False, create_constraint=True, length=11), nullable=False),
    sa.Column('cvss_score_used', sa.Float(), nullable=True),
    sa.Column('cvss_version_used', sa.String(length=8), nullable=True),
    sa.Column('cvss_source_used', sa.String(length=128), nullable=True),
    sa.Column('epss_initial_used', sa.Float(), nullable=True),
    sa.Column('epss_current_at_assessment', sa.Float(), nullable=True),
    sa.Column('base_time', app.models.types.UTCDateTime(), nullable=False),
    sa.Column('due_at_computed', app.models.types.UTCDateTime(), nullable=True),
    sa.Column('calc_method', sa.String(length=128), nullable=True),
    sa.Column('reason', sa.String(length=512), nullable=False),
    sa.Column('assessed_at', app.models.types.UTCDateTime(), nullable=False),
    sa.CheckConstraint("assessment_state IN ('assessed', 'epss_pending')", name='ck_va_assessment_state'),
    sa.CheckConstraint("assessment_state IN ('assessed', 'epss_pending')", name='ck_va_assessment_state'),
    sa.CheckConstraint("zone IN ('경계면', '내부')", name='ck_va_zone'),
    sa.CheckConstraint("zone IN ('경계면', '내부')", name='ck_va_zone'),
    sa.ForeignKeyConstraint(['asset_vulnerability_id'], ['asset_vulnerabilities.id'], ),
    sa.ForeignKeyConstraint(['policy_version_id'], ['policy_versions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('vulnerability_assessments', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_vulnerability_assessments_asset_vulnerability_id'), ['asset_vulnerability_id'], unique=False)

    # ### end Alembic commands ###
    # 무결성 보호 Trigger (append-only / 불변 컬럼)
    install_db_guards(op.get_bind())


def downgrade() -> None:
    """Downgrade schema."""
    if op.get_bind().dialect.name == "postgresql":
        for fn in ("vp_forbid_change", "vp_epss_initial_immutable",
                   "vp_initial_due_immutable", "vp_policy_immutable"):
            op.execute(f"DROP FUNCTION IF EXISTS {fn}() CASCADE")
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('vulnerability_assessments', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_vulnerability_assessments_asset_vulnerability_id'))

    op.drop_table('vulnerability_assessments')
    with op.batch_alter_table('status_history', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_status_history_asset_vulnerability_id'))

    op.drop_table('status_history')
    with op.batch_alter_table('mapping_candidates', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_mapping_candidates_cve_id'))
        batch_op.drop_index(batch_op.f('ix_mapping_candidates_asset_product_id'))

    op.drop_table('mapping_candidates')
    with op.batch_alter_table('asset_vulnerabilities', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_asset_vulnerabilities_status'))
        batch_op.drop_index(batch_op.f('ix_asset_vulnerabilities_severity'))
        batch_op.drop_index(batch_op.f('ix_asset_vulnerabilities_owner'))
        batch_op.drop_index(batch_op.f('ix_asset_vulnerabilities_due_at'))
        batch_op.drop_index(batch_op.f('ix_asset_vulnerabilities_cve_id'))
        batch_op.drop_index(batch_op.f('ix_asset_vulnerabilities_asset_product_id'))
        batch_op.drop_index(batch_op.f('ix_asset_vulnerabilities_asset_id'))

    op.drop_table('asset_vulnerabilities')
    with op.batch_alter_table('asset_products', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_asset_products_vendor_norm'))
        batch_op.drop_index(batch_op.f('ix_asset_products_product_norm'))
        batch_op.drop_index(batch_op.f('ix_asset_products_cpe_normalized'))
        batch_op.drop_index(batch_op.f('ix_asset_products_asset_id'))

    op.drop_table('asset_products')
    with op.batch_alter_table('vulnerability_products', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_vulnerability_products_vendor'))
        batch_op.drop_index(batch_op.f('ix_vulnerability_products_product'))
        batch_op.drop_index(batch_op.f('ix_vulnerability_products_cve_id'))

    op.drop_table('vulnerability_products')
    with op.batch_alter_table('epss_history', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_epss_history_cve_id'))

    op.drop_table('epss_history')
    with op.batch_alter_table('assets', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_assets_owner_name'))
        batch_op.drop_index(batch_op.f('ix_assets_name'))
        batch_op.drop_index(batch_op.f('ix_assets_ip'))
        batch_op.drop_index(batch_op.f('ix_assets_asset_code'))

    op.drop_table('assets')
    with op.batch_alter_table('vulnerabilities', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_vulnerabilities_last_modified_at'))
        batch_op.drop_index(batch_op.f('ix_vulnerabilities_kev'))
        batch_op.drop_index(batch_op.f('ix_vulnerabilities_cvss_score'))

    op.drop_table('vulnerabilities')
    op.drop_table('users')
    with op.batch_alter_table('policy_versions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_policy_versions_is_active'))

    op.drop_table('policy_versions')
    op.drop_table('job_locks')
    op.drop_table('import_batches')
    op.drop_table('collection_history')
    with op.batch_alter_table('audit_logs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_audit_logs_occurred_at'))
        batch_op.drop_index(batch_op.f('ix_audit_logs_actor'))
        batch_op.drop_index(batch_op.f('ix_audit_logs_action'))

    op.drop_table('audit_logs')
    with op.batch_alter_table('asset_product_mapping', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_asset_product_mapping_vendor_norm'))
        batch_op.drop_index(batch_op.f('ix_asset_product_mapping_product_norm'))

    op.drop_table('asset_product_mapping')
    # ### end Alembic commands ###
