"""collector support

Revision ID: 0002
Revises: 0001
Create Date: 2026-09-28 04:44:36.679211

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

import app.models.types
from app.models.guards import install_db_guards


# revision identifiers, used by Alembic.
revision: str = '0002'
down_revision: Union[str, Sequence[str], None] = '0001'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('kev_entries',
    sa.Column('cve_id', sa.String(length=32), nullable=False),
    sa.Column('vendor_project', sa.String(length=256), nullable=True),
    sa.Column('product', sa.String(length=256), nullable=True),
    sa.Column('vulnerability_name', sa.String(length=512), nullable=True),
    sa.Column('date_added', sa.Date(), nullable=False),
    sa.Column('due_date', sa.Date(), nullable=True),
    sa.Column('known_ransomware', sa.String(length=16), nullable=True),
    sa.Column('catalog_version_last_seen', sa.String(length=32), nullable=True),
    sa.Column('first_collected_at', app.models.types.UTCDateTime(), nullable=False),
    sa.Column('last_seen_at', app.models.types.UTCDateTime(), nullable=False),
    sa.PrimaryKeyConstraint('cve_id')
    )
    op.create_table('sync_state',
    sa.Column('key', sa.String(length=320), nullable=False),
    sa.Column('value', sa.String(length=64), nullable=False),
    sa.Column('updated_at', app.models.types.UTCDateTime(), nullable=False),
    sa.PrimaryKeyConstraint('key')
    )
    with op.batch_alter_table('vulnerabilities', schema=None) as batch_op:
        batch_op.add_column(sa.Column('cvss_metrics', sa.JSON(), nullable=False, server_default='[]'))
        batch_op.add_column(sa.Column('nvd_cisa_exploit_add', sa.Date(), nullable=True))
        batch_op.add_column(sa.Column('kev_source', sa.String(length=32), nullable=True))

    with op.batch_alter_table('vulnerability_products', schema=None) as batch_op:
        batch_op.add_column(sa.Column('config_negate', sa.Boolean(), nullable=False, server_default=sa.false()))

    # ### end Alembic commands ###
    # SQLite batch 작업으로 테이블이 재생성된 경우 Trigger 재설치 (IF NOT EXISTS)
    if op.get_bind().dialect.name == "sqlite":
        install_db_guards(op.get_bind())


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('vulnerability_products', schema=None) as batch_op:
        batch_op.drop_column('config_negate')

    with op.batch_alter_table('vulnerabilities', schema=None) as batch_op:
        batch_op.drop_column('kev_source')
        batch_op.drop_column('nvd_cisa_exploit_add')
        batch_op.drop_column('cvss_metrics')

    op.drop_table('sync_state')
    op.drop_table('kev_entries')
    # ### end Alembic commands ###
