"""asset product active flag

Revision ID: 0003
Revises: 0002
Create Date: 2026-09-28 06:00:02.197636

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

from app.models.guards import install_db_guards


# revision identifiers, used by Alembic.
revision: str = '0003'
down_revision: Union[str, Sequence[str], None] = '0002'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('asset_products', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_active', sa.Boolean(), nullable=False, server_default=sa.true()))

    # ### end Alembic commands ###
    if op.get_bind().dialect.name == "sqlite":
        install_db_guards(op.get_bind())


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('asset_products', schema=None) as batch_op:
        batch_op.drop_column('is_active')

    # ### end Alembic commands ###
