"""owner override

Revision ID: 0004
Revises: 0003
Create Date: 2026-09-28 07:31:42.022513

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

from app.models.guards import install_db_guards


# revision identifiers, used by Alembic.
revision: str = '0004'
down_revision: Union[str, Sequence[str], None] = '0003'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('asset_vulnerabilities', schema=None) as batch_op:
        batch_op.add_column(sa.Column('owner_override', sa.Boolean(), nullable=False, server_default=sa.false()))

    # ### end Alembic commands ###
    if op.get_bind().dialect.name == "sqlite":
        install_db_guards(op.get_bind())


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('asset_vulnerabilities', schema=None) as batch_op:
        batch_op.drop_column('owner_override')

    # ### end Alembic commands ###
